version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: demo_app:0.1
    ports:
      - "5000:5000"
    networks:
      - app
  app_test:
    build:
      context: ./test
      dockerfile: Dockerfile
    image: demo_app_test:0.1
    ports:
      - "5001:5001"
    networks:
      - app
    links:
      - app
      - clickhouse
  clickhouse:
     image: yandex/clickhouse-server
     

networks:
  app:
